{
 "title": "Docker Container Dashboard",
 "description": "Docker Monitoring Template",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Proxy Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_user_seconds_total{name=\"which_squid_1\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Proxy Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"which_squid_1\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Proxy Container Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"which_squid_1\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}